<?php $form->setAttribute('class', 'form-horizontal')->prepare() ?>
<?php echo $this->form()->openTag($form) ?>
<div class="form-group<?php if (count($form->get('title')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="name">Title <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('title')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('title'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('description')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="description">Description</label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('description')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('description'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-lg btn-primary">Create</button>
    </div>
</div>
<?php
echo $this->form()->closeTag()?>