<?php $this->headTitle('Закази')?>
<div class="container">
    <div class="page-header">
        <?php if($this->acl('application-home/orders-add')):?>
        <a class="btn btn-success pull-right" href="<?php echo $this->url('order', array('action'=>'add'))?>"><i class="fa fa-plus"></i> Добавити заказ</a>
        <?php endif?>
        <h3>Закази (<?php echo $this->paginator->getTotalItemCount()?>)</h3>
    </div>
    <div class="well">
        <?php $form->setAttribute('class', 'form-inline')->prepare() ?>
        <?php echo $this->form()->openTag($form) ?>
            <div class="form-group">
                <label for="exampleInputName2">Пошуковий запит</label>
                <?php echo $this->formElement($form->get('query')->setAttribute('class', 'form-control')) ?>
            </div>
            <?php if($this->auth()->getUserRow()->role!='member'):?>
            <div class="form-group">
                <label for="exampleInputName2">Майстер</label>
                <?php echo $this->formElement($form->get('user_id')->setAttribute('class', 'form-control')) ?>
            </div>
            <?php endif?>
            <div class="form-group">
                <label for="exampleInputName2">Статус</label>
                <?php echo $this->formElement($form->get('status')->setAttribute('class', 'form-control')) ?>
            </div>
            <div class="form-group">
                <label for="exampleInputName2">Тип товару</label>
                <?php echo $this->formElement($form->get('category_id')->setAttribute('class', 'form-control')) ?>
            </div>
            <button class="btn btn-primary" type="submit">Шукати</button>
            <?php if(count($form->getWhere())):?>
            <a class="btn btn-default" href="<?php echo $this->url('order')?>">Скинути</a>
            <?php endif?>
        <?php echo $this->form()->closeTag()?>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Номер заказа
                </th>
                <th>
                    Дата створення
                </th>
                <th>
                    ПІБ
                </th>
                <?php if($this->auth()->getUserRow()->role!='member'):?>
                <th>
                    Номер телефону
                </th>
                <?php endif?>
                <th>
                    Сумма
                </th>
                <?php if($this->auth()->getUserRow()->role!='member'):?>
                <th>
                    Майстер
                </th>
                <?php else:?>
                <th>
                    Менеджер
                </th>
                <?php endif?>
                <th>
                    Статус
                </th>
                <th width="200">
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($paginator AS $item):?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('order', array('action'=>'view'))?>?id=<?php echo $item->id?>">Заказ № <?php echo $item->id?></a>
                </td>
                <td>
                    <span data-time="<?php echo $item->time_add?>" data-format="H:i d/m/Y"><?php echo date('H:i d/m/Y', $item->time_add)?>
                </td>
                <td>
                    <?php echo $item->customer_name?>
                </td>
                <?php if($this->auth()->getUserRow()->role!='member'):?>
                <td>
                    +380 <?php echo $item->customer_phone?>
                </td>
                <?php endif?>
                <td>
                    <?php if($this->auth()->getUserRow()->role!='member'):?>
                    <?php echo $item->price?> грн.
                    <?php else:?>
                    <?php echo $item->getUserPrice()?> грн.
                    <?php endif?>
                </td>
                <?php if($this->auth()->getUserRow()->role!='member'):?>
                <td>
                    <?php if($item->user_id && $item->getUserRow()):?>
                    <?php echo $item->getUserRow()->name?>
                    <?php else:?>
                    - - 
                    <?php endif?>
                </td>
                <?php else:?>
                <td>
                    <?php if($item->acceptor_id && $item->getAcceptorRow()):?>
                    <?php echo $item->getAcceptorRow()->name?>
                    <?php else:?>
                    - - 
                    <?php endif?>
                </td>
                <?php endif?>
                <td>
                    <?php if ($item->getStatusRow()->is_default == 'yes'): ?>
                        <span class="label label-warning"><?php echo $item->getStatusRow()->name?></span>
                    <?php elseif ($item->getStatusRow()->is_close == 'yes'): ?>
                        <span class="label label-default"><?php echo $item->getStatusRow()->name?></span>
                    <?php else: ?>
                        <span class="label label-success"><?php echo $item->getStatusRow()->name?></span>
                    <?php endif ?>
                </td>
                <td class="text-right">
                    <a target="_blank" href="<?php echo $this->url('order', array('action'=>'print'))?>?id=<?php echo $item->id?>" class="btn btn-default"><i class="fa fa-print"></i></a>
                    <a href="<?php echo $this->url('order', array('action'=>'view'))?>?id=<?php echo $item->id?>" class="btn btn-info"><i class="fa fa-eye"></i></a>
                    <?php if($this->acl('application-home/orders-edit')):?>
                    <a href="<?php echo $this->url('order', array('action'=>'edit'))?>?id=<?php echo $item->id?>" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                    <?php endif?>
                    <?php if($this->acl('application-home/orders-remove')):?>
                    <a href="<?php echo $this->url('order', array('action'=>'remove'))?>?id=<?php echo $item->id?>" class="btn btn-danger" onclick="return confirm('Видалити?');"><i class="fa fa-trash"></i></a>
                    <?php endif?>
                </td>
            </tr>
            <?php endforeach;?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->paginator,
        'Sliding',
        'paginator.phtml', array('params'=>array(), 'query'=>$form->getData(), 'route'=>'order')); ?>
</div>