<?php $v = 1 ?>
<head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
    <?php echo $this->headTitle('Black_Mine')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <script src="/js/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath('/css/font-awesome.min.css') ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath('/css/style.css') ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath('/css/bootstrap.min.css') ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath('/css/jquery.share.css') ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath('/css/bootstrap.min.css') ?>"/>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->themePath('/css/style.css') ?>"/>
    <link href="<?php echo $this->themePath('/favicon.png') ?>" rel="shortcut icon" type="image/png"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"/>
    <base href="<?php echo $this->basePath('/') ?>"/>
</head>
