<div class="row">
    <div class="col-sm-6">
        <?php $form->setAttribute('class', 'form')->prepare() ?>
        <?php echo $this->form()->openTag($form) ?>
        <div class="form-group<?php if (count($form->get('title')->getMessages())): ?> has-error<?php endif ?>">
            <label class="control-label" for="name">Title <font color="red">*</font></label>
            <div class="controls">
                <?php echo $this->formElement($form->get('title')->setAttribute('class', 'form-control')) ?>
                <?php echo $this->formElementErrors($form->get('title'), array('class' => 'text-danger')); ?>
            </div>
        </div>
        <div class="form-group<?php if (count($form->get('description')->getMessages())): ?> has-error<?php endif ?>">
            <label class="control-label" for="description">Description</label>
            <div class="controls">
                <?php echo $this->formElement($form->get('description')->setAttribute('class', 'form-control')) ?>
                <?php echo $this->formElementErrors($form->get('description'), array('class' => 'text-danger')); ?>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="controls">
        <button class="btn btn-lg btn-primary">Save</button>
    </div>
</div>
<?php echo $this->form()->closeTag()?>