<?php $this->headTitle($title = 'Settings') ?>
<?php $this->headTitle($projectRow->title) ?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li><a href="<?php echo $this->url('projects')?>">Projects</a></li>
        <li><a href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id))?>"><?php echo $projectRow->title?></a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <h3><?php echo $this->escapeHtml($title)?></h3>
        </div>
        
        <div>
            <ul class="nav nav-tabs" role="tablist">
              <li class="active"><a href="#home">Information</a></li>
              <li><a href="#profile">Members</a></li>
              <li><a href="#messages">Messages</a></li>
              <li><a href="#settings">Settings</a></li>
            </ul>
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active">
              
              </div>
            </div>
        </div>
    </div>
</div>