<?php $this->headTitle('Про нас')?>
<div class="home-image"></div>

<div class="about-info">
    <div class="block-with-header">
        <div class="block-header text-center">
            <img src="img/icons/people.png" alt=""> <h1>Про сервісний центр “FixTechPro”</h1>
        </div>

        <div class="block-body">
            <p>Сервісний центр &ldquo;<strong>FixTechPro</strong>&rdquo; &nbsp;пропонує великий спектр послуг з ремонту комп&rsquo;ютерноЇ техніки&nbsp;(ноутбуків, системних блоків, моніторів, планшетів та ін.)</p>

            <p>Безпосередньо займаємося:</p>

            <p>1. Діагностикою та &nbsp;ремонтом &nbsp;материнських плат, в тому числі: &nbsp; &nbsp;</p>

            <ul>
                <li>перепайка BGA - чіпів (північний/південний мости); &nbsp; &nbsp;</li>
                <li>заміну відеокарт/відеочіпів; &nbsp; &nbsp; &nbsp;</li>
                <li>&nbsp;ремонт/заміну роз&#39;ємів живлення, USB - портів, звукових роз&#39;ємів; &nbsp; &nbsp;</li>
            </ul>

            <p>2. Модульною заміною комплектуючих ноутбука:</p>

            <ul>
                <li>клавіатури; &nbsp; &nbsp; &nbsp; &nbsp;</li>
                <li>матриці; &nbsp; &nbsp; &nbsp; &nbsp;</li>
                <li>CD-DVD/R-RW; &nbsp; &nbsp; &nbsp; &nbsp;</li>
                <li>оперативної пам&rsquo;яті; &nbsp; &nbsp; &nbsp; &nbsp;</li>
                <li>жорсткого диска; &nbsp; &nbsp; &nbsp; &nbsp;</li>
                <li>акумулятора; &nbsp; &nbsp;</li>
            </ul>

            <p>3. Відновленням/перепрошивкою BIOS &nbsp; &nbsp;</p>
            <p>4. Ремонтом підсвітки ноутбука &nbsp; &nbsp;</p>
            <p>5. Чисткою системи охолодження &nbsp; &nbsp;</p>
            <p>6. Заміною/ремонтом внутрішніх шлейфів &nbsp; &nbsp;</p>
            <p>7. Заміною або відновленням корпусних деталей ноутбука &nbsp; &nbsp;</p>
            <p>8. Модернізацією ноутбука &nbsp; &nbsp;</p>
            <p>9. Заміною сенсорів, дисплеїв, роз`ємів на планшетах &nbsp; &nbsp;</p>
            <p>10. Ремонтом зарядних пристроїв (БЖ)</p>
        </div>
    </div>
</div>
