<?php $this->headTitle('Project management web application') ?>
<div class="index-intro-header">
    <section class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>
                    Project management web application
                </h1>
                <span class="version">
                    Version 1.0
                </span>
                <p>
                    <strong>Black_Mine</strong> is open source and released under the terms of the <a target="_blank" href="http://www.gnu.org/licenses/old-licenses/gpl-2.0.html">GNU General Public License v2</a> (GPL)
                </p>
            </div>
        </div>
    </section>
</div>
<div class="index-intro-body">
    <div class="index-intro-demos">
        <div class="container">
            <div class="row">
                <div class="demo demo-left clearfix">
                    <div class="col-sm-5">
                        <div class="demo-design">
                            <img src="img/demo.png" class="design img-responsive">
                        </div>
                    </div>
                    <div class="col-sm-7">
                        <div class="demo-content">
                            <h3>
                                Business theme
                            </h3>
                            <p>
                                Includes templates for startups, businesses, web &amp; mobile apps,  photographers, restaurants. Bundled with pricing pages, different blog layouts, careers, customer support, success stories, sign in, timelines, and much more!
                            </p>
                            <a href="index.html" class="btn btn-lg btn-success btn-shadow" target="_blank">
                                Browse demo
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="demo demo-right clearfix">
                    <div class="col-sm-7">
                        <div class="demo-content">
                            <h3>
                                Agency &amp; creative theme
                            </h3>
                            <p>
                                Includes templates to showcase your work and portfolio, your team and culture, a full client project, forms for contact and for new business opportunities to start new projects.
                            </p>
                            <a href="agency.html" class="btn btn-lg btn-success btn-shadow" target="_blank">
                                Browse demo
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="demo-design">
                            <img src="img/demo.png" class="design img-responsive">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="index-intro-features">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="icon">
                        <i class="fa fa-save"></i>
                    </div>
                    <h4>
                        Free updates and support
                    </h4>
                    <p>
                        This theme includes free updates and technical support, including the next upgrade for Bootstrap 4. <a href="mailto:e.adrian90@gmail.com">Send us an email</a> and we'll get back to you as soon as possible.
                    </p>
                </div>
                <div class="col-sm-4">
                    <div class="icon">
                        <i class="fa fa-save"></i>
                    </div>
                    <h4>
                        Source files and tooling
                    </h4>
                    <p>
                        Includes all the source and compiled files you need, plus Gulp based build tools for compiling, minifying and optimizing everything you need.
                    </p>
                </div>
                <div class="col-sm-4">
                    <div class="icon">
                        <i class="fa fa-save"></i>
                    </div>
                    <h4>
                        Great documentation
                    </h4>
                    <p>
                        We've included <a href="theme-docs.html" target="_blank">detailed documentation</a> to easily get started, make changes and customizations, plus live examples for new components and plugins.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="index-intro">
        <div class="container">
            <div class="header">
                <h3>How does it actually work?</h3>
                <p>
                    Spacial has both a web app and an android app to make your website easy and always available. It offers you all the designs in collaboration with some smart people. Your projects will look great everywhere you go.
                </p>
            </div>
            <section class="row">
                <div class="col-sm-6">
                    <h4>Take all your photos at all times</h4>
                    <p>
                        Spacial is the perfect solution for web developers and designers. You can get an awesome website for your best projects and clients, and also get support for any questions and matters that you might have.
                    </p>
                </div>
                <div class="col-sm-6">
                    <h4>Upgrade your account to get all features</h4>
                    <p>
                        Spacial is designed to make showing off your best projects extremely fast and simple. There are many ways to configure. Just go to the source, make changes and the rest is taken care automatically.
                    </p>
                </div>
            </section>
        </div>
    </div>
    <div class="index-devices">
        <section class="clearfix">
            <img src="img/devices-4.png" class="devices">
            <h4>Looks great in any device</h4>
            <p>
                Spacial has both a web app and an android app to make your website easy and always available. It offers you all the designs in collaboration with some smart people. Your projects will look great everywhere you go. Use new components that come included!
            </p>
            <p>
                Spacial is an advanced theme solution for desktop, tablet, and mobile devices. It works in all browsers and your clients can pay instantly, to improve their experience at all times anywhere they go.
            </p>
            <div class="icons">
                <i class="fa fa-television icon-monitor"></i>
                <i class="fa fa-tablet icon-tablet"></i>
                <i class="fa fa-mobile icon-mobile"></i>
            </div>
        </section>
    </div>
</div>