<?php $this->headTitle('Pricing') ?>
<div class="container">
    <div class="page-header">
        <h2>Black_Mine Pricing</h2>
    </div>
    <div id="pricing-charts-tabs" class="pricing-charts-tabs">
        <div class="tabs clearfix">
            <a class="tab monthly" data-tab="monthly">
                <span>Monthly Billing</span>
            </a>
            <a class="tab annual active" data-tab="annually">
                <span>Annual Billing</span>
                <span class="discount label label-success">
                    20% off
                </span>
            </a>
        </div>
    </div>
    <div class="pricing-charts">
        <div class="chart">
            <div class="header">
                <div class="name">Beginner</div>
                <div class="price monthly">
                    <span class="currency">$</span>
                    <span class="qty">19</span>
                    <span class="period">/mo</span>
                </div>
                <div class="price annually active">
                    <span class="currency">$</span>
                    <span class="qty">182</span>
                    <span class="period">/year</span>
                </div>
            </div>
            <section class="features">
                <div class="feature">
                    10 users
                </div>
                <div class="feature">
                    3 projects
                </div>
                <div class="feature">
                    <strong>5GB</strong> 
                    data storage
                </div>
                <div class="feature">
                    <strong>2</strong> 
                    templates
                </div>
            </section>
            <div class="action">
                <a href="#" class="btn btn-primary btn-lg">
                    Choose Plan
                </a>
            </div>
        </div>
        <div class="chart">
            <div class="header">
                <div class="name">Professional</div>
                <div class="price monthly">
                    <span class="currency">$</span>
                    <span class="qty">89</span>
                    <span class="period">/mo</span>
                </div>
                <div class="price annually active">
                    <span class="currency">$</span>
                    <span class="qty">854</span>
                    <span class="period">/year</span>
                </div>
            </div>
            <section class="features">
                <div class="feature">
                    30 users
                </div>
                <div class="feature">
                    10 projects
                </div>
                <div class="feature">
                    Email support
                </div>
                <div class="feature">
                    <strong>30GB</strong> 
                    data storage
                </div>
                <div class="feature">
                    Security Policy
                </div>
                <div class="feature">
                    <strong>5</strong> 
                    templates
                </div>
            </section>
            <div class="action">
                <a href="#" class="btn btn-primary btn-lg">
                    Choose Plan
                </a>
            </div>
        </div>
        <div class="chart">
            <div class="header">
                <div class="name">Enterprise</div>
                <div class="price monthly">
                    <span class="currency">$</span>
                    <span class="qty">149</span>
                    <span class="period">/mo</span>
                </div>
                <div class="price annually active">
                    <span class="currency">$</span>
                    <span class="qty">1430</span>
                    <span class="period">/year</span>
                </div>
            </div>
            <section class="features">
                <div class="feature">
                    Unlimited users
                </div>
                <div class="feature">
                    Unlimited projects
                </div>
                <div class="feature">
                    Email support
                </div>
                <div class="feature">
                    <strong>100GB</strong> 
                    data storage
                </div>
                <div class="feature">
                    Security Policy
                </div>
                <div class="feature">
                    <strong>Unlimited</strong> 
                    templates
                </div>
            </section>
            <div class="action">
                <a href="#" class="btn btn-primary btn-lg">
                    Choose Plan
                </a>
            </div>
        </div>
    </div>
    <h3>Additional Services</h3>
    <div class="pricing-plans">
        <div class="wrapper">
            <div class="plans">
                <div class="plan clearfix">
                    <div class="name">Team</div>
                    <div class="users">3 users</div>
                    <div class="price">
                        $7 <small>/mo</small>
                    </div>
                    <div class="choose">
                        <a href="#" class="btn btn-default">Buy Now</a>
                    </div>
                </div>
                <div class="plan clearfix">
                    <div class="name">Startup</div>
                    <div class="users">10 users</div>
                    <div class="price">
                        $19 <small>/mo</small>
                    </div>
                    <div class="choose">
                        <a href="#" class="btn btn-default">Buy Now</a>
                    </div>
                </div>
                <div class="plan clearfix">
                    <div class="name">Professional</div>
                    <div class="users">20 users</div>
                    <div class="price">
                        $79 <small>/mo</small>
                    </div>
                    <div class="choose">
                        <a href="#" class="btn btn-primary">Buy Now</a>
                    </div>
                </div>
                <div class="plan clearfix">
                    <div class="name">Enterprise</div>
                    <div class="users">Unlimited users</div>
                    <div class="price">
                        $129 <small>/mo</small>
                    </div>
                    <div class="choose">
                        <a href="#" class="btn btn-default">Buy Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>