<?php $form->setAttribute('class', 'form-horizontal')->prepare() ?>
<?php echo $this->form()->openTag($form) ?>
<div class="form-group<?php if (count($form->get('name')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="name">Name <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('name')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('name'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('email')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="email">Email <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('email')->setAttribute('class', 'form-control')->setAttribute('autocomplete', 'off')) ?>
        <?php echo $this->formElementErrors($form->get('email'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('password')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="password">Password <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('password')->setAttribute('class', 'form-control')->setAttribute('autocomplete', 'off')) ?>
        <?php echo $this->formElementErrors($form->get('password'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('password_again')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="password_again">Password again <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('password_again')->setAttribute('class', 'form-control')->setAttribute('autocomplete', 'off')) ?>
        <?php echo $this->formElementErrors($form->get('password_again'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-lg btn-primary">Create</button>
        <button type="submit" name="continue" class="btn btn-lg btn-primary">Create and continue</button>
    </div>
</div>
<?php echo $this->form()->closeTag()?>