<?php $this->headTitle($title = 'Users') ?>
<?php $this->headTitle('Administration') ?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li><a href="<?php echo $this->url('admin')?>">Administration</a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <?php if($this->acl('application-admin/users-add')):?>
            <a class="btn btn-sm btn-success pull-right" href="<?php echo $this->url('admin', array('controller'=>'users', 'action'=>'add'))?>"><i class="fa fa-plus"></i> Add user</a>
            <?php endif?>
            <h3><?php echo $title?></h3>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Administrator</th>
                    <th>Created</th>
                    <th>Last connection</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($paginator AS $item):?>
                <tr>
                    <td>
                        <?php echo $this->escapeHtml($item->getUserRow()->name)?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($item->getUserRow()->email)?>
                    </td>
                    <td>
                        <?php if($item->is_admin=='on'):?>
                        <i class="fa fa-check"></i>
                        <?php endif?>
                    </td>
                    <td>
                        <span data-time="<?php echo $item->time_add?>" data-format="H:i d/m/Y"></span>
                    </td>
                    <td class="text-right">
                        <?php if($this->acl('application-admin/users-remove')):?>
                        <a href="<?php echo $this->url('admin', array('controller'=>'users', 'action'=>'remove'))?>?id=<?php echo $item->id?>" class="btn btn-sm btn-danger" onclick="return confirm('Unlink?');"><i class="fa fa-unlink"></i></a>
                        <?php endif?>
                    </td>
                </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>
</div>