<?php $form->setAttribute('class', 'form-horizontal')->prepare() ?>
<?php echo $this->form()->openTag($form) ?>
<div class="form-group<?php if (count($form->get('type_id')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="type_id">Type <font color="red">*</font></label>
    <div class="col-sm-2">
        <?php echo $this->formElement($form->get('type_id')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('type_id'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('title')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="name">Title <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('title')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('title'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('status_id')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="status_id">Status <font color="red">*</font></label>
    <div class="col-sm-2">
        <?php echo $this->formElement($form->get('status_id')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('status_id'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('assignee_id')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="assignee_id">Assignee</label>
    <div class="col-sm-2">
        <?php echo $this->formElement($form->get('assignee_id')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('assignee_id'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('priority_id')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="priority_id">Priority <font color="red">*</font></label>
    <div class="col-sm-2">
        <?php echo $this->formElement($form->get('priority_id')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('priority_id'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('category_id')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="category_id">Category</label>
    <div class="col-sm-2">
        <?php echo $this->formElement($form->get('category_id')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('category_id'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group<?php if (count($form->get('description')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="description">Description</label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('description')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('description'), array('class' => 'text-danger')); ?>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-lg btn-primary">Create</button>
        <button type="submit" name="continue" class="btn btn-lg btn-primary">Create and continue</button>
    </div>
</div>
<?php
echo $this->form()->closeTag()?>