<?php $this->headTitle($title = 'Tasks') ?>
<?php $this->headTitle($projectRow->title) ?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li><a href="<?php echo $this->url('projects')?>">Projects</a></li>
        <li><a href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id))?>"><?php echo $projectRow->title?></a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <?php if($this->acl('application-home/project/tasks-add')):?>
            <a class="btn btn-sm btn-success pull-right" href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id,'controller'=>'tasks', 'action'=>'add'))?>"><i class="fa fa-plus"></i> New task</a>
            <?php endif?>
            <h3><?php echo $this->escapeHtml($title)?></h3>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Priority</th>
                    <th>Title</th>
                    <th>Assignee</th>
                    <th>Updated</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($paginator AS $item):?>
                <?php $url = $this->url('project-view', array('project_id'=>$projectRow->id, 'controller'=>'tasks', 'action'=>'view'), array('query'=>array('id'=>$item->id)))?>
                <tr>
                    <td>
                        <a href="<?php echo $url?>">
                            <?php echo $item->id?>
                        </a>
                    </td>
                    <td>
                        <?php if($item->type_id):?>
                        <?php echo $this->escapeHtml($item->getTypeRow()->name)?>
                        <?php else:?>
                        - - 
                        <?php endif?>
                    </td>
                    <td>
                        <?php if($item->status_id):?>
                        <?php echo $this->escapeHtml($item->getStatusRow()->name)?>
                        <?php else:?>
                        - - 
                        <?php endif?>
                    </td>
                    <td>
                        <?php if($item->priority_id):?>
                        <?php echo $this->escapeHtml($item->getPriorityRow()->name)?>
                        <?php else:?>
                        - - 
                        <?php endif?>
                    </td>
                    <td>
                        <a href="<?php echo $url?>">
                            <?php echo $this->escapeHtml($item->title)?>
                        </a>
                    </td>
                    <td>
                        <?php if($item->assignee_id):?>
                        <?php if($item->getAssigneeRow()):?>
                        <a href="<?php echo $this->url('user-view', array('user_id'=>$item->assignee_id))?>">
                            <?php echo $this->escapeHtml($item->getAssigneeRow()->title)?>
                        </a>
                        <?php else:?>
                        <i>Remove user #<?php echo $item->assignee_id?></i>
                        <?php endif?>
                        <?php else:?>
                        - - 
                        <?php endif?>
                    </td>
                    <td>
                        <?php echo date('H:i d/m/Y', $item->time_update)?>
                    </td>
                    <td class="text-right">
                        <?php if($this->acl('application-home/project/tasks-update')):?>
                        <a href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id, 'controller'=>'tasks', 'action'=>'update'))?>?id=<?php echo $item->id?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                        <?php endif?>
                        <?php if($this->acl('application-home/project/tasks-remove')):?>
                        <a href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id, 'controller'=>'tasks', 'action'=>'remove'))?>?id=<?php echo $item->id?>" class="btn btn-sm btn-danger" onclick="return confirm('Видалити?');"><i class="fa fa-trash"></i></a>
                        <?php endif?>
                    </td>
                </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>
</div>