<div class="row">
    <div class="col-sm-6">
        <?php $form->setAttribute('class', 'form')->prepare() ?>
        <?php echo $this->form()->openTag($form) ?>
        <div class="form-group<?php if (count($form->get('title')->getMessages())): ?> has-error<?php endif ?>">
            <label class="control-label" for="title">Title <font color="red">*</font></label>
            <div class="controls">
                <?php echo $this->formElement($form->get('title')->setAttribute('class', 'form-control')) ?>
                <?php echo $this->formElementErrors($form->get('title'), array('class' => 'text-danger')); ?>
            </div>
        </div>
        <div class="form-group<?php if (count($form->get('email')->getMessages())): ?> has-error<?php endif ?>">
            <label class="control-label" for="email">Email</label>
            <div class="controls">
                <?php echo $this->formElement($form->get('email')->setAttribute('class', 'form-control')) ?>
                <?php echo $this->formElementErrors($form->get('email'), array('class' => 'text-danger')); ?>
            </div>
        </div>
        <div class="form-group<?php if (count($form->get('phone')->getMessages())): ?> has-error<?php endif ?>">
            <label class="control-label" for="phone">Phone</label>
            <div class="controls">
                <div class="input-group">
                    <div class="input-group-addon">+</div>
                    <?php echo $this->formElement($form->get('phone')->setAttribute('class', 'form-control')) ?>
                </div>
                <?php echo $this->formElementErrors($form->get('phone'), array('class' => 'text-danger')); ?>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="form-group<?php if (count($form->get('description')->getMessages())): ?> has-error<?php endif ?>">
            <label class="control-label" for="description">Comment / Description</label>
            <div class="controls">
                <?php echo $this->formElement($form->get('description')->setAttribute('class', 'form-control')->setAttribute('rows', '10')) ?>
                <?php echo $this->formElementErrors($form->get('description'), array('class' => 'text-danger')); ?>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="controls">
        <button class="btn btn-lg btn-primary">Save</button>
    </div>
</div>
<?php echo $this->form()->closeTag()?>