<?php $this->headTitle($title = 'Edit customer') ?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li><a href="<?php echo $this->url('customers')?>">Customers</a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <h3><?php echo $this->escapeHtml($title)?></h3>
        </div>
        <?php echo $this->render('_form.phtml')?>
    </div>
</div>