<?php $this->headTitle($title = 'News') ?>
<?php $this->headTitle($projectRow->title) ?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li><a href="<?php echo $this->url('projects')?>">Projects</a></li>
        <li><a href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id))?>"><?php echo $projectRow->title?></a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <?php if($this->acl('application-home/project-add')):?>
            <a class="btn btn-sm btn-success pull-right" href="<?php echo $this->url('project-view', array('project_id'=>$projectRow->id,'controller'=>'news', 'action'=>'add'))?>"><i class="fa fa-plus"></i> Add new</a>
            <?php endif?>
            <h3><?php echo $this->escapeHtml($title)?></h3>
        </div>
    </div>
</div>