<?php $this->headTitle($title = 'Login page') ?>
<div class="container">
    <?php if (isset($form)): ?>
    <?php echo $this->flashMessages() ?>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <?php $form->setAttribute('class', 'form')->prepare() ?>
            <?php echo $this->form()->openTag($form) ?>
            <div class="form-group<?php if (count($form->get('email')->getMessages())): ?> error<?php endif ?>">
                <div class="controls">
                    <?php echo $this->formElement($form->get('email')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Email')) ?>
                    <?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-inline')); ?>
                </div>
            </div>
            <div class="form-group<?php if (count($form->get('password')->getMessages())): ?> error<?php endif ?>">
                <div class="controls">
                    <?php echo $this->formElement($form->get('password')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Password')) ?>
                    <?php echo $this->formElementErrors($form->get('password'), array('class' => 'help-inline')); ?>
                </div>
            </div>
            <?php if ($captchaStatus): ?>
                <div class="form-group<?php if ($this->captchaError): ?> error<?php endif ?>">
                    <div class="controls">
                        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                        <div class="g-recaptcha" data-sitekey="<?php echo $captchaKey ?>"></div>
                        <?php if ($this->captchaError): ?>
                            <ul class="help-inline"><li><?php echo implode('<br/>', $captcha->getMessages()) ?></li></ul>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif ?>
            <div class="form-group">
                <button class="btn btn-primary btn-lg btn-block">Log in</button>
            </div>
            <div class="form-group">
                <a href="/auth/forgot">Forgot your password?</a>
            </div>
            <div class="form-group">
                <p>Don't have an account yet? <a href="/auth/signup">Sign up</a>
            </div>
            <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
    <?php endif?>
</div>