<?php $form->setAttribute('class', 'form-horizontal')->prepare() ?>
<?php echo $this->form()->openTag($form) ?>
<div class="form-group<?php if (count($form->get('name')->getMessages())): ?> has-error<?php endif ?>">
    <label class="col-sm-2 control-label" for="name">Name <font color="red">*</font></label>
    <div class="col-sm-10">
        <?php echo $this->formElement($form->get('name')->setAttribute('class', 'form-control')) ?>
        <?php echo $this->formElementErrors($form->get('name'), array('class' => 'text-danger')); ?>
    </div>
</div>
<legend>Permissions</legend>
<?php foreach($form->getPermissions() AS $items):?>
<div class="form-group">
    <label class="col-sm-2 control-label" for="name"><?php echo $items['label']?></label>
    <div class="col-sm-10">
        <div class="row">
            <?php foreach($items['childs'] AS $item):?>
            <div class="col-sm-3">
                <div class="checkbox">
                    <label> 
                        <?php echo $this->formElement($form->get($item['resource']))?> <?php echo $item['label']?>
                    </label>
                </div>
            </div>
            <?php endforeach?>
        </div>
    </div>
</div>
<?php endforeach?>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-lg btn-primary">Create</button>
    </div>
</div>
<?php
echo $this->form()->closeTag()?>