<?php $this->headTitle($title = 'Role and permissions') ?>
<?php $this->headTitle('Administration') ?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li><a href="<?php echo $this->url('admin')?>">Administration</a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <?php if($this->acl('application-admin/permissions-add')):?>
            <a class="btn btn-sm btn-success pull-right" href="<?php echo $this->url('admin', array('controller'=>'permissions', 'action'=>'add'))?>"><i class="fa fa-plus"></i> New role</a>
            <?php endif?>
            <h3><?php echo $title?></h3>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($paginator AS $item):?>
                <tr>
                    <td>
                        <?php echo $this->escapeHtml($item->name)?>
                    </td>
                    <td class="text-right">
                        <?php if($this->acl('application-admin/permissions-add')):?>
                        <a href="<?php echo $this->url('admin', array( 'controller'=>'permissions', 'action'=>'add'))?>?copy=<?php echo $item->id?>" class="btn btn-sm btn-info"><i class="fa fa-files-o"></i></a>
                        <?php endif?>
                        <?php if($this->acl('application-admin/permissions-edit')):?>
                        <a href="<?php echo $this->url('admin', array( 'controller'=>'permissions', 'action'=>'edit'))?>?id=<?php echo $item->id?>" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                        <?php endif?>
                        <?php if($this->acl('application-admin/permissions-remove')):?>
                        <a href="<?php echo $this->url('admin', array( 'controller'=>'permissions', 'action'=>'remove'))?>?id=<?php echo $item->id?>" class="btn btn-sm btn-danger" onclick="return confirm('Видалити?');"><i class="fa fa-trash"></i></a>
                        <?php endif?>
                    </td>
                </tr>
                <?php endforeach?>
            </tbody>
        </table>
    </div>
</div>