<?php $this->headTitle($title = 'Customers')?>
<div class="container">
    <ul class="breadcrumb">
        <li>
            <a href="/"><i class="fa fa-home" aria-hidden="true"></i></a>
        </li>
        <li><a href="/home">Dashboard</a></li>
        <li>
            <?php echo $title?>
        </li>
    </ul>
    <div class="container-fluid">
        <div class="page-header">
            <?php if($this->acl('application-home/customer-add')):?>
            <a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url('customer', array('action'=>'add'))?>"><i class="fa fa-plus"></i> Add customer</a>
            <?php endif?>
            <h4><?php echo $title?> (<?php echo $this->paginator->getTotalItemCount()?>)</h4>
        </div>
        <div class="well well-sm">
            <?php $form->setAttribute('class', 'form-inline')->prepare() ?>
            <?php echo $this->form()->openTag($form) ?>
                <div class="form-group">
                    <?php echo $this->formElement($form->get('query')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Search query')) ?>
                </div>
                <button class="btn btn-primary" type="submit"><i class="fa fa-filter"></i> Filter</button>
                <?php if(count($form->getWhere())):?>
                <a class="btn btn-default" href="<?php echo $this->url('customer')?>">Cancel</a>
                <?php endif?>
            <?php echo $this->form()->closeTag()?>
        </div>
        <?php if(count($paginator)):?>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Phone
                    </th>
                    <th width="150">
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($paginator AS $item):?>
                <tr>
                    <td>
                        <?php echo $item->id?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($item->title)?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($item->email)?>
                    </td>
                    <td>
                        <?php echo $this->escapeHtml($item->phone)?>
                    </td>
                    <td class="text-right">
                        <?php if($this->acl('application-home/customer-edit')):?>
                        <a href="<?php echo $this->url('customer', array('action'=>'edit'))?>?id=<?php echo $item->id?>" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                        <?php endif?>
                        <?php if($this->acl('application-home/customer-remove')):?>
                        <a href="<?php echo $this->url('customer', array('action'=>'remove'))?>?id=<?php echo $item->id?>" onclick="return confirm('Do you want remove?')" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                        <?php endif?>
                    </td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator,
            'Sliding',
            'paginator.phtml', array('params'=>array(), 'query'=>$form->getData(), 'route'=>'customer')); ?>
        <?php else:?>
        <p>Result not found</p>
        <?php endif?>
    </div>
</div>