<?php echo $this->doctype()."\n"; ?>
<?php  $children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0]; ?>
<?php $cssLayerName = ($child->cssLayerName)?$child->cssLayerName:'default';?>
<html dir='ltr' lang='en'>
    <?php echo $this->render('head.phtml'); ?>
    <body class="sticky-footer layer layer-<?php echo $cssLayerName?>">
        <header>
            <nav class="navbar navbar-transparent" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="navbar-right navbar-btn-container">
                            <?php if ($this->auth()->is()): ?>
                            <a href="<?php echo $this->url('default', array('controller'=>'home'))?>" class="btn navbar-btn btn-transparent"><i class="fa fa-user"></i></a>
                            <?php else:?>
                            <a href="<?php echo $this->url('login')?>" class="btn navbar-btn btn-transparent">Login</a>
                            <?php endif?>
                        </div>
                        <a class="navbar-brand" href="/">
                            <h1>Black_Mine</h1>
                        </a>
                        <div class="navbar-right collapse navbar-collapse" id="navbar-collapse">
                            <?php echo $this->navigation('menu\default')->menu()
                                ->setUlClass('nav navbar-nav navbar-right')
                                ->setMinDepth(0)
                                ->setMaxDepth(1)
                                ->setPartial(array('menu.phtml', 'default')); ?>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <?php echo $this->content ?>
        <?php echo $this->render('footer.phtml'); ?>
        <script src="/js/main.js" type="text/javascript"></script>
    </body>
</html>
